export { default as KeyFact } from './components/KeyFacts/KeyFact.vue'
export { default as KeyFactGroup } from './components/KeyFacts/KeyFactGroup.vue'
export { default as KeyInformation } from './components/KeyInformation/KeyInformation.vue'
export { default as PropertyTaskIntro } from './components/PropertyTaskIntro/PropertyTaskIntro.vue'
export { default as TaskTitle } from './components/TaskTitle/TaskTitle.vue'
export { default as VendorTable } from './components/VendorTable/VendorTable.vue'
